feat: update scilab to 2024.1.0+dfsg-6
Signed-off-by: lhdjply <lhdjply@126.com>

diff --git a/scilab/bin/scilab b/scilab/bin/scilab
--- a/scilab/bin/scilab
+++ b/scilab/bin/scilab
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
+# Scilab ( https://www.scilab.org/ ) - This file is part of Scilab
 # Copyright (C) INRIA - 2006-2008 - Sylvestre Ledru
 # Copyright (C) INRIA - 2008 - Simon Lipp
 # Copyright (C) DIGITEO - 2009-2011 - Sylvestre Ledru
@@ -127,7 +127,7 @@ start_profiling_visu() {
 
 find_docbook_path() {
     if test -z "$DOCBOOK_ROOT"; then
-        for dir in $SCI/thirdparty/docbook /usr/share/sgml/docbook/stylesheet/xsl/nwalsh /usr/share/docbook2X/xslt/man/ /usr/share/xml/docbook/stylesheet/nwalsh/ /usr/share/xml/docbook/stylesheet/nwalsh/current/ /sw/share/xml/xsl/docbook-xsl /usr/share/xml/docbook/xsl-stylesheets-*/ /usr/share/sgml/docbook/xsl-stylesheets-*/ /usr/share/sgml/docbook/xsl-stylesheets /usr/share/sgml/docbook/xsl-ns-stylesheets-*/ /usr/share/xml/docbook/stylesheet/docbook-xsl /opt/local/share/xsl/docbook-xsl; do
+        for dir in $SCI/thirdparty/docbook /usr/share/sgml/docbook/stylesheet/xsl/nwalsh /usr/share/docbook2X/xslt/man/ /usr/share/xml/docbook/stylesheet/nwalsh/ /usr/share/xml/docbook/stylesheet/nwalsh/current/ /usr/share/xml/docbook/xsl-stylesheets-*/ /usr/share/sgml/docbook/xsl-stylesheets-*/ /usr/share/sgml/docbook/xsl-stylesheets /usr/share/sgml/docbook/xsl-ns-stylesheets-*/ /usr/share/xml/docbook/stylesheet/docbook-xsl /opt/local/share/xsl/docbook-xsl; do
             if test -r "$dir/fo/docbook.xsl"; then
                 if test -z "$DOCBOOK_ROOT"; then
                     DOCBOOK_ROOT=$dir
@@ -153,7 +153,7 @@ detect_type_of_scilab(){
         SCILABBIN="scilab-bin"
     fi
 
-    if (echo "$progname"|grep "scilab-cli$" 2>&1 > /dev/null;) || (echo "$@"|grep "\-nwni" 2>&1 > /dev/null;) then
+    if (echo "$progname"|grep "scilab-cli$" 2>&1 > /dev/null;) || (echo "$@"|grep "\-nwni" 2>&1 > /dev/null;) || (echo "$@"|grep "\-nogui" 2>&1 > /dev/null;) then
         SCILAB_MODE="nwni"
         SCILABBIN="scilab-cli-bin"
         DISABLE_JAVA_DETECTION=1
@@ -318,44 +318,7 @@ detect_scilab_path() {
 detect_macos_vm() {
     # java_home -arch flag is broken on macOS Big Sur
     # we take the first JVM matching version and architecture
-    echo $(/usr/libexec/java_home -v 1.8 -X | xmllint --format  --xpath "(//string[preceding-sibling::key[text()='JVMHomePath']][1][preceding-sibling::string[text()='$ARCH']])[1]/text()" -)
-}
-
-set_macosx_java_vm () {
-    # For Mac OS X we have to detect the CPU
-    if test -z "$DEVENV"; then
-        # this method supposes no fat binary
-        export ARCH=$(echo $(lipo -archs "$SCI/../../bin/$SCILABBIN"))
-    else
-        export ARCH=$(echo $(lipo -archs "$SCI/.libs/scilab-bin"))
-    fi
-    if test -z "$JAVA_HOME"; then
-        JAVA_HOME=$(detect_macos_vm)
-        if test -z "$JAVA_HOME"; then
-            open -W jre/Scilab\ JRE\ Install.app
-            JAVA_HOME=$(detect_macos_vm)
-            if test -z "$JAVA_HOME"; then
-                exit 1
-            fi
-        fi
-    fi
-    # Add JNI capability, typically needed for Oracle JDK
-    PLIST=$JAVA_HOME/../Info.plist
-    if [[ $(plutil -extract JavaVM json -o - $PLIST) == *"JVMCapabilities"* && $(plutil -extract JavaVM.JVMCapabilities json -o - $PLIST) != *"JNI"* ]]; then
-        PROMPT="A Java Runtime Edition has been found at $JAVA_HOME and needs to be allowed to run Scilab (once for all)"
-        osascript -e "do shell script \"plutil -insert JavaVM.JVMCapabilities.0 -string JNI $PLIST\" with prompt \"$PROMPT \" with administrator privileges"
-        if test $? -eq 1; then
-            exit 1
-        fi
-    fi
-    JAVA_JVM_VERSION=$JAVA_HOME
-    export JAVA_JVM_VERSION
-    DYLD_LIBRARY_PATH=$JAVA_HOME/lib/server:$JAVA_HOME/jre/lib/server:$DYLD_LIBRARY_PATH
-    # All working JRE/JDK under BigSur/arm64 need this to find libjava.dylib
-    if test $ARCH == arm64; then
-        DYLD_LIBRARY_PATH=$JAVA_HOME/lib/:$JAVA_HOME/jre/lib/:$DYLD_LIBRARY_PATH
-    fi
-
+    echo $(/usr/libexec/java_home -v 17 -X | xmllint --format  --xpath "(//string[preceding-sibling::key[text()='JVMHomePath']][1][preceding-sibling::string[text()='$ARCH']])[1]/text()" -)
 }
 
 set_embedded_java_vm () {
@@ -374,12 +337,29 @@ set_embedded_java_vm () {
                         proc="i386"
                         ;;
                     *)
-                        echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us on http://bugzilla.scilab.org"
+                        echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us on https://gitlab.com/scilab/scilab/-/issues"
                         ;;
                 esac
                 ;;
+            Darwin)
+                export ARCH=$(uname -m)
+                # If Scilab does not have an embedded jre we try to detect a system installed one
+                # if not found we prompt the user for installation
+                if test ! -f $SCIBINARYBASE/thirdparty/jre/lib/libjli.dylib; then
+                    JAVA_HOME=$(detect_macos_vm)
+                    if test -z "$JAVA_HOME"; then
+                        open -W "jre/Scilab JRE Install.app"
+                        JAVA_HOME=$(detect_macos_vm)
+                        if test -z "$JAVA_HOME"; then
+                            exit 1
+                        fi
+                    fi
+                    # Add detected jre path to libjli.dylib
+                    DYLD_LIBRARY_PATH="$(dirname $(find $JAVA_HOME  -name libjli.dylib))"
+                fi
+                ;;
             *)
-            echo "Could not find the Java configuration for the OS <${OS}>. Please contact us or submit a bug report with your detailed configuration http://bugzilla.scilab.org/"
+            echo "Could not find the Java configuration for the OS <${OS}>. Please contact us or submit a bug report with your detailed configuration https://gitlab.com/scilab/scilab/-/issues"
             echo "Fallback on the model <${MODEL}> found by uname -m"
             proc=$MODEL
             ;;
@@ -429,9 +409,7 @@ detect_java_vm() {
 
     JAVA_SHLIB="libjava.so"
 
-    if test $OS = "Darwin"; then
-        set_macosx_java_vm
-    elif test $IS_SCILAB_BINARY -eq 1; then
+    if test $IS_SCILAB_BINARY -eq 1; then
         set_embedded_java_vm
     else  # NOT IS_SCILAB_BINARY
 
@@ -477,7 +455,7 @@ detect_java_vm() {
 # Browse "default directory" (if it means anything under Unix/Linux) of Java
 # to find where it could be !
             if test -z "$JAVA_HOME"; then
-                JAVA_DEFAULT_DIR="/usr/java/jdk1.8.*/ /usr/lib/jvm/java-1.8.0-*/ /usr/lib/jvm/java-8-*/ /etc/alternatives/java_sdk /etc/alternatives/jre /usr/java/jdk*/ /usr/lib/jvm/java-*/"
+                JAVA_DEFAULT_DIR="/usr/java/jdk17.*/ /usr/lib/jvm/java-1.17.0-*/ /usr/lib/jvm/java-17-*/ /etc/alternatives/java_sdk /etc/alternatives/jre /usr/java/jdk*/ /usr/lib/jvm/java-*/"
                 for DIR in $JAVA_DEFAULT_DIR ; do
                     if test $SCIVERBOSE -ne 0; then
                         echo "Trying to find Java in $DIR "
@@ -596,7 +574,7 @@ detect_java_vm() {
                             proc="aarch64"
                             ;;
                         *)
-                            echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us on http://bugzilla.scilab.org"
+                            echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us on https://gitlab.com/scilab/scilab/-/issues"
                             ;;
                     esac
                     ;;
@@ -629,8 +607,11 @@ detect_java_vm() {
                 *FreeBSD*)
                     proc=$MODEL
                     ;;
+                Darwin)
+                    proc=$MODEL
+                    ;;
                 *)
-                    echo "Could not find the Java configuration for the OS <${OS}>. Please contact us or submit a bug report with your detailed configuration http://bugzilla.scilab.org/"
+                    echo "Could not find the Java configuration for the OS <${OS}>. Please contact us or submit a bug report with your detailed configuration https://gitlab.com/scilab/scilab/-/issues"
                     echo "Fallback on the model <${MODEL}> found by uname -m"
                     proc=$MODEL
                     ;;
@@ -639,7 +620,7 @@ detect_java_vm() {
     fi # IS_SCILAB_BINARY
 
     # Check if the lib exists
-    LIBJAVA="$JRE_HOME/lib/$proc/$JAVA_SHLIB"
+    LIBJAVA="$JRE_HOME/lib/$JAVA_SHLIB"
     if test ! -f "$LIBJAVA"; then
         if test $SCIVERBOSE -ne 0; then
             echo "Cannot find $LIBJAVA"
@@ -648,10 +629,10 @@ detect_java_vm() {
         CLASSPATH="${CLASSPATH:+:$CLASSPATH}$SCI/modules/core/jar/org.scilab.modules.core.jar"
         # @TODO This is the default path of the official sun JVM.
         # It is different for other implementation of the JVM....
-        LD_LIBRARY_PATH="$JRE_HOME/lib/$proc/:$JRE_HOME/lib/$proc/server/:$JRE_HOME/lib/$proc/native_threads/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
+        LD_LIBRARY_PATH="$JRE_HOME/lib/:$JRE_HOME/lib/server/:$JRE_HOME/lib/native_threads/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
     fi
 
-    # Bug http://bugzilla.scilab.org/show_bug.cgi?id=14290 -
+    # Bug https://gitlab.com/scilab/scilab/-/issues/14290 -
     # Never run headless on Mac (unless explicitly asked through
     # the SCI_JAVA_ENABLE_HEADLESS option -- which will not work anyway)
     case $OS in
@@ -697,10 +678,8 @@ if test $IS_SCILAB_BINARY -eq 1; then
 
     case $OS in
         *darwin* | *Darwin*)
-            DYLD_LIBRARY_PATH=$SCIBINARYBASE/lib/scilab:$SCIBINARYBASE/lib/thirdparty${DYLD_LIBRARY_PATH+:$DYLD_LIBRARY_PATH}
-            export DYLD_LIBRARY_PATH
-            PATH="/sw/bin:/sw64/bin:$PATH"
-            export PATH
+            DYLD_FALLBACK_LIBRARY_PATH=$SCIBINARYBASE/lib/thirdparty
+            export DYLD_FALLBACK_LIBRARY_PATH
             ;;
     esac
 
@@ -716,7 +695,7 @@ else
 fi
 
 
-# See http://bugzilla.scilab.org/show_bug.cgi?id=3486
+# See https://gitlab.com/scilab/scilab/-/issues/3486
 # Some Java stuff raises spurious SIGSEGV. The problem is that when bug-buddy
 # is enabled, it catches the signal and terminate Scilab. We have to
 # desactivate bug-buddy.
@@ -727,7 +706,7 @@ export GTK_MODULES
 
 # libEGL may be partially supported by the closed-source NVIDIA driver.
 # Until they release an EGL driver, we force the egl_glx driver.
-# http://bugzilla.scilab.org/show_bug.cgi?id=12940
+# https://gitlab.com/scilab/scilab/-/issues/12940
 if test $SCILAB_MODE != "nwni" -a -x /usr/bin/glxinfo; then
     NVIDIA_GLX_VENDOR=$(/usr/bin/glxinfo |grep "NVIDIA Corporation")
     if test ! -z "$NVIDIA_GLX_VENDOR"; then
@@ -779,7 +758,7 @@ dialog_try_or_exit()
 
 fail_macosx_version()
 {
-    dialog_try_or_exit "This version of Scilab may fail on this system ($macosxVersion): Scilab is currently supported from 10.13 (High Sierra) to 11 (Big Sur)."
+    dialog_try_or_exit "This version of Scilab may fail on this system ($macosxVersion): Scilab is currently supported from macOS 10.13 (High Sierra) to macOS 14 (Sonoma)."
 }
 check_macosx_version()
 {
@@ -793,7 +772,7 @@ check_macosx_version()
                     ;;
             esac
             ;;
-        11)
+        11|12|13|14)
             ;;
         *)
             fail_macosx_version
@@ -813,8 +792,6 @@ fi
 
 case $OS in
     *darwin* | *Darwin*) # MacOS X
-        # When using some packaging tools like fink which are storing the info in /sw/lib
-        LD_LIBRARY_PATH="/sw/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
     # Export the path to the Scilab lib when Scilab has been install ...
     # to a Mac os x specific variable used by the linker before LD_LIBRARY_PATH
         DYLD_LIBRARY_PATH=$SCI/../../lib/scilab/${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}:
@@ -955,7 +932,15 @@ do_scilex()
         if test "$SCILAB_MODE" = "scinotes"; then
             do_scinotes "$@"
         else
-            "$SCILABBIN" "$@"
+            if test "$OS" = "Darwin" -a $IS_SCILAB_BINARY -eq 1; then
+                if test "$(file $BINPATH/$SCILABBIN | awk '{print $NF}')" =  "arm64"; then
+                    arch -arch arm64 "$SCILABBIN" "$@"
+                else
+                    "$SCILABBIN" "$@"
+                fi
+            else
+                "$SCILABBIN" "$@"
+            fi
             exit $?
         fi
     fi
@@ -1061,8 +1046,7 @@ if test "$OS" = "Darwin"; then
 fi
 
 MORE_OPT=""
-echo " $@ " | grep " \-nw " 2>&1 > /dev/null
-if ([ $? != 0 ];) && (test "$SCILAB_MODE" = "nw";) then
+if (echo "$@"|grep -v "\-nw" 2>&1 > /dev/null;) && (test "$SCILAB_MODE" = "nw";) then
     MORE_OPT="-nw"
 fi
 
@@ -1099,7 +1083,7 @@ if test "$rest" = "yes"; then
         fi
 
         case $sciarg in
-            -nogui|-version|-ns|-nb|-nouserstartup|-noatomsautoload|-nocolor|--texmacs)
+            -version|-ns|-nb|-nouserstartup|-noatomsautoload|-nocolor|--texmacs)
                 ;;
             -nw)
                 if test "$SCILAB_MODE" = "nwni"; then
@@ -1107,9 +1091,9 @@ if test "$rest" = "yes"; then
                     exit 5
                 fi
                 ;;
-            -nwni)
+            -nwni|-nogui)
                 if test "$SCILAB_MODE" = "nw"; then
-                    echo "Cannot use scilab-adv-cli with option -nwni"
+                    echo "Cannot use scilab-adv-cli with option -nwni or -nogui"
                     exit 5
                 fi
                 ;;
